# Generated by Django 5.2.6 on 2025-09-30 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants_manager', '0002_remove_insurancecompany_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('claims_overview', 'Claims Overview'), ('financial_summary', 'Financial Summary'), ('adjuster_performance', 'Adjuster Performance'), ('policy_type_analysis', 'Policy Type Analysis')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filters', models.JSONField(default=dict)),
                ('report_data', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants_manager.insurancecompany')),
            ],
        ),
    ]
