# Generated by Django 5.2.6 on 2025-10-03 14:35

import claims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('assigned', 'Assigned'), ('under_review', 'Under Review'), ('investigation', 'Investigation'), ('documents_requested', 'Documents Requested'), ('waiting_approval', 'Waiting Approval'), ('approved', 'Approved'), ('denied', 'Denied'), ('payment_processing', 'Payment Processing'), ('paid', 'Paid'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('incident_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('police_report', 'Police Report'), ('estimate', 'Repair Estimate'), ('photo', 'Photo'), ('medical_bill', 'Medical Bill'), ('invoice', 'Invoice'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to=claims.models.get_file_name)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
