# Generated by Django 5.2.6 on 2025-09-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('assigned', 'Assigned'), ('under_review', 'Under Review'), ('investigation', 'Investigation'), ('documents_requested', 'Documents Requested'), ('waiting_approval', 'Waiting Approval'), ('approved', 'Approved'), ('denied', 'Denied'), ('payment_processing', 'Payment Processing'), ('paid', 'Paid'), ('closed', 'Closed')], default='reported', max_length=20),
        ),
    ]
