# Generated by Django 5.2.6 on 2025-10-03 14:35

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('business_type', models.CharField(choices=[('auto', 'Auto Insurance'), ('health', 'Health Insurance'), ('property', 'Property Insurance'), ('life', 'Life Insurance'), ('multi_line', 'Multi-Line Insurance')], max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('linkedin', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.TextField(blank=True)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('subscription_plan', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('auto', 'Auto Insurance'), ('health', 'Health Insurance'), ('property', 'Property Insurance'), ('life', 'Life Insurance'), ('multi_line', 'Multi-Line Insurance')], max_length=50)),
                ('company_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('company_address', models.TextField()),
                ('company_linkedin', models.CharField(blank=True, max_length=150, null=True)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('subscription_plan', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', max_length=20)),
                ('requested_domain', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_phone', models.CharField(max_length=15)),
                ('admin_first_name', models.CharField(max_length=30)),
                ('admin_last_name', models.CharField(max_length=30)),
                ('admin_username', models.CharField(max_length=30)),
                ('admin_password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants_manager.insurancecompany')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
