# Generated by Django 5.2.6 on 2025-09-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancecompany',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='linkedin',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
