# Generated by Django 5.2.6 on 2025-10-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_manager', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='  ', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
