# Generated by Django 5.2.6 on 2025-10-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_manager', '0002_remove_insurancecompany_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('business_type', models.CharField(choices=[('auto', 'Auto Insurance'), ('health', 'Health Insurance'), ('property', 'Property Insurance'), ('life', 'Life Insurance'), ('multi_line', 'Multi-Line Insurance')], max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('linkedin', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.TextField(blank=True)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('subscription_plan', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', max_length=20)),
                ('requested_domain', models.CharField(max_length=100)),
            ],
        ),
    ]
