# Generated by Django 5.2.6 on 2025-09-24 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('policyholder_name', models.CharField(max_length=100)),
                ('policyholder_email', models.EmailField(max_length=254)),
                ('policy_type', models.CharField(choices=[('auto', 'Auto'), ('home', 'Home'), ('life', 'Life'), ('health', 'Health'), ('business', 'Business'), ('travel', 'Travel'), ('other', 'Other')], max_length=20)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants_manager.insurancecompany')),
            ],
        ),
    ]
