# Generated by Django 5.2.6 on 2025-09-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('tenant', 'Tenant')], default='tenant', max_length=10),
        ),
    ]
